version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=smart-contract-audit

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/smart-contract-audit
        - AI_DETECTOR_URL=http://ai-detector:5002

      - PORT=5000
      - NODE_ENV=development
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - smart-contract-audit-network

  analysis-engine:
    build: ./analysis-engine
    ports:
      - "5001:5001"
    volumes:
      - ./analysis-engine:/app
      - /app/node_modules
    depends_on:
      - backend

  compliance-checker:
    build: ./compliance-checker
    ports:
      - "5002:5002"
    volumes:
      - ./compliance-checker:/app
      - /app/node_modules
    depends_on:
      - backend

  reports-service:
    build: ./reports-service
    ports:
      - "5003:5003"
    volumes:
      - ./reports-service:/app
      - ./analysis-engine:/app/analysis-engine
      - ./compliance-checker:/app/compliance-checker
      - /app/node_modules
    depends_on:
      - backend
      - analysis-engine
      - compliance-checker

  ai-detector:
    build: ./ai-detector
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
    volumes:
      - ./ai-detector:/app
      - ./ai-detector/models:/app/models
    depends_on:
      - backend
    networks:
      - smart-contract-audit-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mongo-data:
